### ISSUE TITLE
nsd zone.list thread safety

### ISSUE THREAD

**Issue by and0x000** [NLnetLabs/nsd#101]
I have the problem, that I have a setup with a rather high frequency of calls of `nsd-control` with the   `addzone`/`delzone` commands. I noticed, that occasionally I have garbage lines in my zone.list file, where the commands are written down.

Like `add foooooaddd bar.tld pattern`. The garbage looks like 2 add commands were somehow merged.

A colleague and I dug a bit through the C code and have the suspicion, that the garbage data comes from writing data to the zone.list not being thread safe.

https://github.com/NLnetLabs/nsd/blob/master/remote.c#L1365 indicates to me, that some concern was put into this by using a task to add data into the diff file.
However, for interaction with the zone.list file, only a plain function call to [`zone_list_add`](https://github.com/NLnetLabs/nsd/blob/master/options.c#L438) is performed, which does not look like it guarantees any form of thread safety.

Is there a way to ensure thread safety for this in recent NSD 4.3.1?

**Comment by wcawijngaards** [comment]
The function is started from a single thread.  From a single process.  So 1358 adds it to the file.  The tasklist is for hosting the zone in the server for queries.  The xfrd process is the one that services the nsd-control channel, and there is only one, and it is single threaded.  So there cannot be a thread thing.

Are you running multiple NSD instances, with the same zone.list file?

**Comment by and0x000** [comment]
I am running multiple instances via the `server-count` option, if that's what you mean.

Processlist for nsd:
```
~ # ps fax | grep nsd
26417 ?        Ss     5:03 /usr/sbin/nsd -d
26518 ?        S     71:03  \_ /usr/sbin/nsd -d
13971 ?        S      0:00      \_ /usr/sbin/nsd -d
13972 ?        S      0:00      \_ /usr/sbin/nsd -d
13973 ?        S      0:00      \_ /usr/sbin/nsd -d
13974 ?        S      0:00      \_ /usr/sbin/nsd -d
13975 ?        S      0:00      \_ /usr/sbin/nsd -d
13976 ?        S      0:00      \_ /usr/sbin/nsd -d
13977 ?        S      0:00      \_ /usr/sbin/nsd -d
13978 ?        S      0:00      \_ /usr/sbin/nsd -d
```

**Comment by wcawijngaards** [comment]
No that is not what I meant.

Since there is no threading issues possible, what corrupts the zone.list file?  Another process, perhaps a script, is modifying the file?  NSD opens it and writes to it.

I was asking if you had another NSD server running, eg. started with the same or similar config file that is also attempting to write to the zone.list file?  The ps output seems to indicate not that case.

**Comment by and0x000** [comment]
Ok, if I understand you correctly, NSD does not have a worker concept for the HTTP interface (unlike "real" HTTP servers such as nginx or apache). The individual HTTP requests are blocking, thus no serialization for the caused actions (such as writes to the zone.list) is necessary.

No, there are (or should be) no other processes/scripts, that interact with the zone list. However, I had some segfaults in NSD 4.2.4 (for which I upgraded to NSD 4.3.1). Best guess would be, that these segfaults may have caused the corruption.

Will keep an eye on this, but that seems to be a different topic then. Thank you for your time and effort. Always amazing to see, how fast you react to issues.
