### ISSUE TITLE
nsd.conf documentation on nlnetlabs.nl outdated

### ISSUE THREAD

**Issue by and0x000** [NLnetLabs/nsd#114]
The nsd.conf documentation on https://www.nlnetlabs.nl/documentation/nsd/nsd.conf/ seems a bit outdated.

It lacks several configuration options, that are available in NSD for quite some time. Notable example: the ratelimit parameters.

**Comment by wcawijngaards** [comment]
I think this is not because it is outdated but because that page is not compiled with ratelimiting enabled.  If ratelimits are not enabled, they are also not displayed in the man page.

**Comment by wcawijngaards** [comment]
Fixed, the page contains the ratelimit options now,
https://www.nlnetlabs.nl/documentation/nsd/nsd.conf/#rrl-ratelimit
Thanks for the report!
