### ISSUE TITLE
order of inclusion facing config.h

### ISSUE THREAD

**Issue by magenbluten** [NLnetLabs/nsd#124]
the current inclusion order of various headers is a bit off. for example the file `buffer.h` directly includes libc headers:

https://github.com/NLnetLabs/nsd/blob/4043a5ab7be7abaec969011e48e4d0d60a0056a6/buffer.h#L16

however the buffer implementation in `buffer.c` also includes libc headers but including `config.h` before them. 
that can result, because config.h can influence the features of the libc, in an "inconsistent" view on those headers.

it would be better to make `config.h` ( unfortunately ) an interface dependency and be sure to be included before
and system libc header? ( this is a minor nitpicky issue for sure )

**Comment by wcawijngaards** [comment]
Yes we should include config.h before other headers.  The includes are there in buffer.h, because it has inline code.

**Comment by magenbluten** [comment]
looking at namedb.{c,h} it is done twice. in "opposite" order.

**Comment by wcawijngaards** [comment]
This does not happen in the code because the buffer.h file is not included before config.h.  Otherwise you would be right.
