### ISSUE TITLE
error: sendmmsg [0]=[redactedip] count=1 failed: Invalid argument

### ISSUE THREAD

**Issue by SvenVD-be** [NLnetLabs/nsd#128]
Hi,

We sometimes have these messages in the logs? error: sendmmsg [0]=[redactedip] count=1 failed: Invalid argument

How to resolve them? What is the root cause?

Version nsd: nsd-4.2.4

Thanks

**Comment by wcawijngaards** [comment]
Likely this is because the IP is in a range where the kernel refuses to send it to.  The invalid part is the netblock of the IP address.  Certain IPv6 range act like this, if they are not connected.  Also other ranges, like multicast or so, or maybe localhost on particular VM set ups.

**Comment by SvenVD-be** [comment]
Thanks for the reply Wouter,

The redacted ip seems like a normal public ipv4 (no multicast, no localhost, no private range). We did have this error for the same [redactedip] on 2 different anycast nodes.

For responses where the kernel does not have a route to we get a different error message.
 error: sendmmsg [0]=[] count=1 failed: No route to host.

Will try to enable more debug.

**Comment by wcawijngaards** [comment]
There was just a bugfix in #129 that fixes the wrong error to get logged.  Perhaps that could help.

**Comment by SvenVD-be** [comment]
Ok, I think I found the issue. On the date the error was logged the [redactedip]  send a query with source port 0. The kernel can not use [redactedip] with source port 0 as a destination address and dst port in the response.

**Comment by wcawijngaards** [comment]
If you want I can also log the port number for these failures?  It would log `ip@port`.

**Comment by SvenVD-be** [comment]
If that would be possible it would be great for troubleshooting.

**Comment by wcawijngaards** [comment]
Ok, sure!  Thanks for the report.

**Comment by shirouzu** [comment]
Hello and FYI, nsd v4.3.5(debian testing) put some error messages.
(OS: Linux 5.10.0-1-amd64 SMP Debian 5.10.4-1 (2020-12-31) x86_64 GNU/Linux)
It seems to occur in response to invalid DNS query packets (source port is zero).
Thanks,

[2021-04-02 16:20:33.069] nsd[28581]: notice: nsd started (NSD 4.3.5), pid 28579
[2021-04-11 12:35:39.214] nsd[28600]: error: sendmmsg [0]=46.174.224.16@0 count=5 failed: Invalid argument
[2021-04-11 18:18:32.648] nsd[28600]: error: sendmmsg [0]=77.65.81.10@0 count=2 failed: Invalid argument
[2021-04-11 18:18:32.649] nsd[28600]: error: sendmmsg [0]=77.65.81.10@0 count=3 failed: Invalid argument
[2021-04-11 21:27:22.922] nsd[28600]: error: sendmmsg [0]=83.31.183.240@0 count=4 failed: Invalid argument

**Comment by wcawijngaards** [comment]
Thank you for the log messages. When the port is zero the entry should be skipped and the remaining messages sent to their requestors. The fix for that is in commit https://github.com/NLnetLabs/nsd/commit/fd00f1318bccf7f8de40a9d02cd2bc72be26c8b5 .

This commit also makes the log message not appear when the verbosity is less than 3. That should keep this out of the logs, unless a high verbosity is used to see more details.
