### ISSUE TITLE
ambiguous use of errno

### ISSUE THREAD

**Issue by magenbluten** [NLnetLabs/nsd#129]
this `errno`:

https://github.com/NLnetLabs/nsd/blob/42552a508cb426e997e79a3ed20f407b4af0b747/server.c#L3389

might be the `errno` of `log_msg`, `fcntl`, the 1st or 2nd `nsd_sendmmsg`.

**Comment by wcawijngaards** [comment]
That was wrong and could have printed the wrong error message if sendmmsg fails.  Fixed in commit https://github.com/NLnetLabs/nsd/commit/8165cb505f07c95cd0e3ec58cf3ac1cbb5fc29c9 .  Thanks for the report!
