### ISSUE TITLE
Stray dot at the end of some log entries

### ISSUE THREAD

**Issue by aabdnn** [NLnetLabs/nsd#13]
I've just noticed an anomaly when parsing NSD logs. Most logs don't end with a dot, but one of the logs looks like this:

```
[2019-06-10 12:22:44.131] nsd[15690]: info: zone arpa. serial 2019061000 is updated to 2019061001.
```

It is unusual for log entries to end with a dot. It doesn't serve any purpose, and in this case, extracting the serial from this line gives me an unexpected value, with a dot at the end.

**Comment by wcawijngaards** [comment]
Fixed, thanks for the report.  I appreciate that the logs can be parsed easily by scripting support, so this good stuff to fix.
