### ISSUE TITLE
nsd open file descriptors

### ISSUE THREAD

**Issue by SvenVD-be** [NLnetLabs/nsd#130]
If you start nsd with systemd it will inherit the default limits of the system:

for i in $(pgrep nsd); do cat /proc/$i/limits | grep open;done 
Max open files            1024                 4096                 files     
Max open files            1024                 4096                 files     
Max open files            1024                 4096                 files   

In contrast to bind/named it does not seem to increase it's own open file limits on startup ( in bind controlled by the 'files' config option )

That means if you set for example tcp-count: to 10000 and tcp-reject-overflow: yes. Then the limit  of tcp clients is not 10000 but more around 4096.

You could override the open file limits with systemd and the  LimitNOFILE option.

Is the above stated correct and recommended way? Or are there other ways to achieve the same.

Thanks

**Comment by wcawijngaards** [comment]
Yes, Unbound attempts to set the setrlimit on start, this requires superuser permissions, and if that fails prints a warning.  And then the user has to adjust the limits with the administration of the system.  For NSD, the user has to set these limits.

**Comment by SvenVD-be** [comment]
Ok thanks that is clear
