### ISSUE TITLE
FreeBSD latest repository is not up to date with the 4.3.3 of NSD

### ISSUE THREAD

**Issue by gearnode** [NLnetLabs/nsd#131]
The version `4.3.3` of NSD is not available on latest repository for FreeBSD 11/12/13. It's voluntary or do you plan to update it soon?

**Comment by wcawijngaards** [comment]
We do not manage the repositories, but those projects do.  Also for Linux distributions.  You would have to contact them to figure out how that is updated.

**Comment by gearnode** [comment]
Thanks!

**Comment by Jakker** [comment]
The FreeBSD committer reacted on this directly, see below.

> Hi!
> 
> _I see you have release the 4.3.3 of NSD yesterday, but it's not
> available for FreeBSD 11/12/13 on the latest repository. Do you plan to
> release it? Do you need help to release this package?_
> 
> It was committed to the HEAD ports tree yesterday. I missed
> committing it to the quarterly tree as a reliability fix,
> but your mail suggests that I should do that (done).
> 
> The quarterly ports tree is rebuild every 3-4 days, as far
> as I know, so it will take a few days to get the fix from
> pkg.freebsd.org.
>

**Comment by gearnode** [comment]
Yes I see, I've send this email, you are faster than me to read a mailbox ;)
