### ISSUE TITLE
IPV4_MINIMAL_RESPONSE_SIZE vs EDNS_MAX_MESSAGE_LEN

### ISSUE THREAD

**Issue by SvenVD-be** [NLnetLabs/nsd#134]
If you compile nsd, then by default IPV4_MINIMAL_RESPONSE_SIZE = 1460. And nsd tries actively to make udp response to fit in that reponse.

However for flag day 2020 EDNS_MAX_MESSAGE_LEN has been set to 1232 (previously 4096) which is less than IPV4_MINIMAL_RESPONSE_SIZE.

I suppose EDNS_MAX_MESSAGE_LEN is the one that ultimately decides the size of the response? Should IPV4_MINIMAL_RESPONSE_SIZE not be set to a value so that it matches the EDNS_MAX_MESSAGE_LEN?

Thanks for clearing this out.

**Comment by wcawijngaards** [comment]
Yes that is a better value for that define.  Fixed it by changing the value, IPv6 value is already lower than that, so I did not adjust that.
