### ISSUE TITLE
NSD returns non-EDNS answer when QUESTION is empty

### ISSUE THREAD

**Issue by anandb-ripencc** [NLnetLabs/nsd#138]
BIND and Knot, when queried with the NSID option set, but with an empty question, return a response containing the NSID. However, NSD fails to do this. IMHO, an NSID query to identify a server does not need a question, and NSD should honour the NSID request and reply with an EDNS response containing the NSID. See below:

```
; <<>> DiG 9.16.8 <<>> +norec +nocookie +nsid +header @BIND
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 26520
;; flags: qr; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; NSID: <omitted>


; <<>> DiG 9.16.8 <<>> +norec +nocookie +nsid +header @KNOT
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOTIMP, id: 13040
;; flags: qr; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; NSID: <omitted>


; <<>> DiG 9.16.8 <<>> +norec +nocookie +nsid +header @NSD 
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 32970
;; flags: qr; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; WARNING: EDNS query returned status FORMERR - retry with '+noedns'
```

**Comment by wcawijngaards** [comment]
The issue is for NSD that is has not parsed the EDNS yet at the time where it rejects the query for not having a question section.

**Comment by anandb-ripencc** [comment]
Yes, I guessed that this is what happens. Do you think this can be changed? My understanding is that a query can have an empty question, but may still have EDNS options for other purposes (cookie probing, identification with NSID).

**Comment by wcawijngaards** [comment]
Yes, but it needs its own EDNS processing calls, for an empty query section.  Which I added, it works when I dig for me without a query section, like you did, and returns the NSID.
