### ISSUE TITLE
DNSTAP logging in NSD-4.2.2

### ISSUE THREAD

**Issue by iruzanov** [NLnetLabs/nsd#146]
I'm happy to share the patchset for NSD-4.2.2 to log both client and local (service) address over DNSTAP (like in Unbound). There is already nsd_socket structure that i use to find pointer to addrinfo structure created when NSD starts. And there is memcpy() syscall i inserted to fill sockaddr_storage structure before dt_collector_submit_auth_* is called. Don't know how its optimal from point of daemon performance. Could you please review the code?

Thank you in advance! 
[patches.tar.gz](https://github.com/NLnetLabs/nsd/files/5667165/patches.tar.gz)

**Comment by wcawijngaards** [comment]
Made a branch to track changes (like for Unbound), and for NSD it is in PR #147 .  That should contain fixes.  There was one length calculation issue for IPv6 logs, and otherwise neater code, by storing the nsd_socket pointer instead of the tcp_read_fd loops are not needed to find the local address.

**Comment by iruzanov** [comment]
I've seen your changes - they look great! I should definitely used tcp_data->socket pointer to save already filled structure. My frivolity :)) Thank you very much for your wise clarifications, Wouter! And for UDP sockets - i kind of used directly data->socket pointers, but the program went to core dump when reuseport=yes was activated. But i played with NSD-4.1.26 at first. And may be i did something wrong in the code. Anyway, i'm waiting for new tarball with patched sources and also binary package to upgrade all of powerfull NSD daemons on my servers ;)

**Comment by wcawijngaards** [comment]
Yes the UDP socket and TCP socket allocation changed in recent NSD versions, so I think that is the difference, and also why it may work now.

**Comment by wcawijngaards** [comment]
There is a tarball with today's code repository with the code branch with changes at https://nlnetlabs.nl/~wouter/nsd-4.3.5-20201210.tar.gz

We do not build binary packages (also not for Unbound), you have to make them yourself, usually package maintainers do it for packaging systems.

**Comment by iruzanov** [comment]
I got it! Thank you, Wouter!
And the package i will make by myself - under FreeBSD its not a problem ;)
