### ISSUE TITLE
CNAME need not be followed after a synthesized CNAME for a CNAME query

### ISSUE THREAD

**Issue by SivaKesava1** [NLnetLabs/nsd#148]
Same issue as in PowerDNS - https://github.com/PowerDNS/pdns/issues/9886

**Comment by wcawijngaards** [comment]
Okay implemented, now for query for type CNAME, the answer is the DNAME and CNAME `foo.c.d.campus.edu. 500 IN CNAME foo.f.d.campus.edu.` and nothing more.
