### ISSUE TITLE
TXT record validation difference with BIND

### ISSUE THREAD

**Issue by and0x000** [NLnetLabs/nsd#150]
I stumbled upon a slight difference in zonfile validation with `nsd-checkzone` compared to the `named-checkzone` from bind9.

Assuming this TXT record in a zonfile:

```
foo       IN  TXT   "a"b
```
Please note, that there is no whitespace between `"a"` and `b`.

* `named-checkzone` considers a zonefile with such a TXT record valid. If loaded into bind, the zonefile is accepted and responds for the record.
* `nsd-checkzone` exits with a syntax error, having such a record in a zonefile also prevents NSD from starting. Only if you add a withespace between `"a"` and `b`, `nsd-checkzone` accepts this.
* `kzonecheck` (knot dns server) has the same behaviour as nsd on this topic.

I could not find the section in any RFC that covers this, but I think zonefiles should be cross compatible with bind providing the reference.

**Comment by wcawijngaards** [comment]
So I wrote the extra parse lines to accept this case, it turns `"a"b` into the string `ab`.  It is nice to have zonefile compatibility.  Thanks for the detailed report.

**Comment by sthen** [comment]
The fix for this breaks records split between multiple lines with parentheses, e.g.

```
test TXT (
  "abcdef"
  "ghijk")
```

Either resulting in just "syntax error", or "nested parentheses" and "syntax error" (I think the latter when there are multiple such records in a zone).

**Comment by sthen** [comment]
Submitted separately as #154 rather than hoping this is seen as a comment on a closed ticket.
