### ISSUE TITLE
DNAME not applied more than once to resolve the query

### ISSUE THREAD

**Issue by SivaKesava1** [NLnetLabs/nsd#151]
Same issue as in Knot: https://gitlab.nic.cz/knot/knot-dns/-/issues/714

**Comment by wcawijngaards** [comment]
It is a feature, not a bug.  The reason is that it is seen as a DNAME loop, because the same DNAME is applied twice.  If it was two different DNAMEs then there would be two DNAMEs in the answer.

**Comment by wcawijngaards** [comment]
But fixed it anyway, because the same behaviour as BIND is desirable.  The fix tests if the CNAME can be added.  That results in the NS record returned in the example you gave.  Thanks for the report!
