### ISSUE TITLE
TXT with parentheses fails in 4.3.5

### ISSUE THREAD

**Issue by sthen** [NLnetLabs/nsd#154]
The fix for #150 breaks records split between multiple lines with parentheses, e.g.

```
test TXT (
  "abcdef"
  "ghijk")
```

Either resulting in just "syntax error", or "nested parentheses" and "syntax error" (I think the latter when there are multiple such records in a zone).

The syntax is used very often with DKIM keys.

**Comment by bes-internal** [comment]
NSD starts with no errors but return old zone (is it cached?) and no return txt records with parentheses and multiline at all!

`nsd-checkzone` is not very helpful in finding the reason, because it just gives out uninformative "syntax error" on next line number

**Comment by wtoorop** [comment]
This is resolved with the merge of PR #164 which also contains a -p option for nsd-checkzone to print the successfully read zone (and aid in debugging these kind of issues).
