### ISSUE TITLE
NSD should check its UID/GID before trying to change them

### ISSUE THREAD

**Issue by ArchangeGabriel** [NLnetLabs/nsd#155]
On Arch Linux, I’ve recently switched nsd to start directly as the nsd user/group rather root and subsequently dropping privileges. Indeed, I could find no reason for it to actually require root.

This works well so far, but user are annoyed by a warning about nsd trying to `initgroups` without success:
`warning: unable to initgroups nsd: Operation not permitted`

Although this seems harmless and expected, it would be better to not emit it. ;)

This is happening in https://github.com/NLnetLabs/nsd/blob/master/nsd.c#1670. I’m not knowledgeable in C, so unable to write a patch, but I guess each try to change user/group or UID/GID in this area of code (they are some instances in the lines above and after) should be preceded by a check whether this is actually needed. ;)

**Comment by wcawijngaards** [comment]
It is possible to set the username as "" in nsd.conf.  Then nsd does not attempt to set the uid and gid.

I think that should stop you from getting that error message.

**Comment by ArchangeGabriel** [comment]
Sorry for the delay, I can confirm this works but since I cannot change this in people configurations, it would still be better if nsd would check whether trying to change is actually required or not. ;)

**Comment by wcawijngaards** [comment]
The packager can set the default for the username, with `./configure --with-user=username`.  If you set that to `""` then you can set it for your users in the package defaults.

**Comment by ArchangeGabriel** [comment]
Awesome, thank you! I’m closing this issue then, because for me this is good enough.
