### ISSUE TITLE
stats: include tls related query stats

### ISSUE THREAD

**Issue by jaredmauch** [NLnetLabs/nsd#16]
for TCP queries, it would be useful to see how many were serviced either by the listening port or served via DoTLS

**Comment by wcawijngaards** [comment]
Added in commit https://github.com/NLnetLabs/nsd/commit/7fe96fbf1ef2ca776b1f917a4ce7269536fe5539
This counts the number of TLS connections.  Those are not counted in the tcp counters. (They were in version 4.2.0, but not after this change, TLS has its own counter separate from TCP).
