### ISSUE TITLE
SVCB and HTTPS

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/nsd#161]
Useful references:
- The draft: https://www.ietf.org/archive/id/draft-ietf-dnsop-svcb-https-03.html
- HOWTO add new RR types in NSD: https://blog.nlnetlabs.nl/howto--add-new-rrtypes-to-nsd/
- HOWTO add new rdata types in NSD: https://lists.nlnetlabs.nl/pipermail/nsd-users/2012-July/001480.html
- Example SVCB implementation in ldns: https://github.com/NLnetLabs/ldns/commit/34da3b2fa4

**Comment by andreasschulze** [comment]
I tried the master branch after https://github.com/NLnetLabs/nsd/commit/1c1958473f8e8e138514658b7ff0569bdacf00b6
SVCB and HTTPS Support works so far, NSD could serve (my simple) records.

But `nsd-checkzone` still fail to understand these records.

**Comment by Glandos** [comment]
#175 says that it works.

In my own setup, it also works.

**Comment by k0ekk0ek** [comment]
Thanks for the reports @andreasschulze and @Glandos! I think these problems have been long fixed, but I'll check before releasing the final 4.10.0 as the new zone parser is now integrated.

**Comment by k0ekk0ek** [comment]
Both RTYPEs are properly supported. Closing this issue.
