### ISSUE TITLE
nsd-control delzone on secondary zones

### ISSUE THREAD

**Issue by and0x000** [NLnetLabs/nsd#165]
I have a secondary zone in my NSD, that I had included via a config file. I wanted it to become a primary zone that is included via a pattern and the zonelist.

When performing the transition, I seem to have messed up some commands. I first added the zone as a primary before de-configuring it as a secondary.

i.e. `nsd-control addzone example.com primary` before removing the secondary config file and running a `nsd-control reconfig`.

Now the zone seems to be in a strange state.

```
nsd-control zonestatus example.com
zone:  example.com
        pattern: primary
        state: refreshing
        served-serial: "2021031401 since 2021-03-15T11:13:46"
        commit-serial: "2021031401 since 2021-03-15T11:13:46"
        wait: "79879 sec between attempts"
```

When I run a `nsd-control delzone example.com`, it removes the zone. However, when I attempt to re-add the zone only with the correct primary pattern, it somewhere picks up the already removed secondary zone data.

```
~ # nsd-control delzone example.com
ok
~ # nsd-control zonestatus example.com
error zone example.com not configured
~ # nsd-control addzone example.com primary
ok
~ # nsd-control zonestatus example.com
zone:   example.com
        pattern: primary
        state: refreshing
        served-serial: "2021031401 since 2021-03-15T11:13:46"
        commit-serial: "2021031401 since 2021-03-15T11:13:46"
        wait: "79879 sec between attempts"
```

NSD is at 4.3.3 but I could not find any fix, that would relate to this issue in 4.3.4 or 4.3.5.

```
NSD version 4.3.3
Written by NLnet Labs.

Configure line: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-configdir=/etc/nsd --with-nsd_conf_file=/etc/nsd/nsd.conf --with-pidfile=/run/nsd/nsd.pid --with-dbfile=/var/lib/nsd/nsd.db --with-zonesdir=/etc/nsd --with-xfrdfile=/var/lib/nsd/xfrd.state --disable-largefile --disable-recvmmsg --enable-root-server --enable-mmap --enable-ratelimit --enable-zone-stats --enable-systemd --enable-checking --enable-dnstap
Event loop: libevent 2.1.8-stable (uses epoll)
Linked with OpenSSL 1.1.1d  10 Sep 2019

Copyright (C) 2001-2020 NLnet Labs.  This is free software.
There is NO warranty; not even for MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.
```

I know that if I restart NSD, the mixed setup is gone, but I would prefer to somehow recover the state without restart. Any ideas?

**Comment by wcawijngaards** [comment]
Can you delzone it and then also remove it from the included config file.  And then touch the config file, so that you can reconfig, after that.  So that it is removed from both the config and zonelist.  And then add it using the method you want, with addzone?

I do not know, but perhaps removing the state and then rereading the config file with the zone not present, gives you a better internal state for the zone; eg. nothing.  And then add it again to get a normal state for the added zone, maybe that works.

**Comment by and0x000** [comment]
Thank you for the quick reply.

> Can you delzone it and then also remove it from the included config file.

After adding the primary pattern, I removed the zone from the config file and ran a reconfig. This resulted in the behavior as described above, picking up the secondary state from somewhere.

I fixed this with the following steps:

- remove the zone via delzone
- created a config file for the zone with a secondary state
- reconfig nsd to load the secondary state for the zone
- remove the config file
- run reconfig again
 
This seems to have resulted in nsd "forgetting" about the zone properly. After doing so, I was able to add the zone with a addzone command as plain primary zone.

If I'd have to guess, I'd say, that nsd did not entirely remove the zone from its internal data structure due to the order I used, but kept the secondary state somewhere and merged the data after re-adding the zone via addzone.

**Comment by wcawijngaards** [comment]
Yes, internally the differences are communicated and those are made active during a change in configuration.  So your order of actions fixed that.

I do not really see a bug here, but the zone available both via config and via zonelist is an issue, but I am not sure how to deal with it.

**Comment by and0x000** [comment]
> I do not really see a bug here, but the zone available both via config and via zonelist is an issue, but I am not sure how to deal with it.

You seem to have some logic in the `delzone` command, that checks, if a zone is configured via file or zonelist.
```
~ # nsd-control delzone example.com
error zone defined in nsd.conf, cannot delete it in this manner: remove it from nsd.conf yourself and repattern
```
Not sure how you do it, but could this check be applied to the `addzone` command as well?

**Comment by wcawijngaards** [comment]
For me, when I try to replicate this, I cannot do it. The existing check in `addzone` says `zone example.com already exists` when I try to add it to NSD while it is already configured from the config file.

If I first: in config file secondary zone. Then remove config entry from config file. nsd-control reconfig. nsd-control addzone as a primary zone. It works fine, and I do not see the failure you are reporting here.

**Comment by and0x000** [comment]
Strange thing, my logs show exactly this sequence, but I cannot reproduce it myself anymore ...

I will close this issue for now until I have a better clue on how the zone achieved this state on my server.

Anyway: Thank you for your time so far.
