### ISSUE TITLE
Disabled IPv6 and DNSTAP enabled triggers a build error

### ISSUE THREAD

**Issue by Jakker** [NLnetLabs/nsd#170]
Building nsd without IPv6 but with DNSTAP fails for FreeBSD. See [https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254874](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254874)

BTW, just building without IPv6 raises a couple of warnings.

**Comment by wcawijngaards** [comment]
Fixed the warnings and also compilation failure. The compilation failure is caused by debug printout wanting to access the ipv6 socket family descriptor when it does not exist. To test for IPv6. Fixed it to not do that when ipv6 is disabled.
