### ISSUE TITLE
nsd-control: no 'listzones'?

### ISSUE THREAD

**Issue by agentgates** [NLnetLabs/nsd#184]
Hi Everyone,

Is there any way to list all the zones in nsd.conf without having to parse the file?
I was looking for an nsd-control subcommand for this purpose. There is 'addzones' and 'delzones' but no 'listzones'?

Does anyone have a spare nsd.conf parser for ksh? :)

Cheers

**Comment by wcawijngaards** [comment]
Hi,

The command `nsd-checkconf -o zones` outputs a list of zones on the output. The output would look like this:
```
example.com
example2.com
example3.com
```
A similar command exists `patterns` that lists all the patterns. nsd-checkconf can also print individual options and is meant for scripting. The man page is here, https://www.nlnetlabs.nl/documentation/nsd/nsd-checkconf/ , look for the `-o` and `-z`, and also the `-s`, `-t` and `-p` options.

If you want to query the running server, does the command `nsd-control zonestatus` help you out here? That shows all the zones, and also their status. It has output like:
```
zone:	example.com
	state: master
zone:	example2.com
	state: master
zone:	example3.com
	state: ok
	served-serial: "2021071600 since 2021-07-23T09:27:35"
	commit-serial: "2021071600 since 2021-07-23T09:27:35"
	wait: "27870 sec between attempts"
```

**Comment by agentgates** [comment]
Hi,

Brilliant! Thanks for the thorough answer, mate.

The first solution you have posted gives me the exact output I was looking, but querying a running server is what I was really after.
So in case anybody needs this in the future, I have processed the output as follows:

`nsd-control zonestatus | grep -a "zone:" | cut -f2`

Again, many thanks!

**Comment by wcawijngaards** [comment]
So that does not need a listzones command, so the issue can be closed. The existing solutions seem fine. Thanks for the scriptlet example.

**Comment by agentgates** [comment]
You are welcome, mate. Here is what I am actually using it for:

`nsd-control zonestatus | grep -a "zone:" | cut -f2 | xargs  -I % sh -c 'echo %; nsd-control force_transfer %; nsd-control write %'`

Basically, next time when I set up a slave, I will run this script on it and it will download all zones from the master.

One more thing, would it be possible to add a wildcard feature in `nsd-control` for referring to all zones?
For example, the above scriptlet could be replaced with the following:
`nsd-control force_transfer *`
`nsd-control write *`

The `*` would refer to all zones, so the command would cycle through them.

Yes, naturally you can close this issue. :)

Thanks for the help, again.
Cheers

**Comment by wcawijngaards** [comment]
NSD already has this wildcard feature, simply leave out the zone name, `nsd-control write` writes all the zones. And also force_transfer is listed that you can leave out the zone name. It then applies to all zones.

NSD also transfers all the zones you configure, if they do not have a zonefile yet, at start. It takes small pauses to deal with large floods, but then transfers all the zones. The zonefiles-write timer could be used to then get the data. So if you have no data yet, just start NSD, wait a couple seconds for the transfers to complete, and then nsd-control write.

**Comment by agentgates** [comment]
Aw okay, thanks mate. Now it makes sense.

At first I was confused by the nsd-control manual as, first of all, it did not explicitly state that without zone name being passed after the `force_transfer` or `write` it will perform those subcommands on all zones.

There is, however, an obscure reference in the section of the `transfer` subcommand to this behaviour:
> "The masters are configured via 'request-xfr:' lists. **If a zone is given**, that zone is updated. Usually NSD receives a NOTIFY from the masters (configured via 'allow-notify:' acl list) that a new zone serial has to be transferred."

IMHO, on its own *"If a zone is given..."* is not straightforward and the other subcommands with `[<zone>]` does not even mention anything near.

Also, the syntax grammar refers to the zones passed as `[<zone>]`. So while `subcommand [variable]` suggests `variable` is *optional*, `subcommand <variable>` suggests `variable` is *mandatory*. Using them together is a little contradictory.

Anyway, thanks for clearing this up.

One more thing. I know what I am suggesting now would require changing the API, but if ever, perhaps in the distant future, it would come to that you have to, would it be possible to prefix the XFR related config options by `xfr-`? For example `notify` would become `xfr-notify`, then `zonefiles-write` would become `xfr-zonefiles-write` or `xfr-write`, etc. They seem to be a little all over the place.

On the other hand, NSD is so far the best authoritative DNS server I have come across in the last 20 years. Keep it up guys! :)

**Comment by wcawijngaards** [comment]
Fixed the man page to note down some commands can operate on all zones. Thank you for the suggestions to improve the configuration.

**Comment by agentgates** [comment]
Okay, thanks. It makes sense now.
