### ISSUE TITLE
Out-of-bounds read caused by improper validation of array index

### ISSUE THREAD

**Issue by fcambus** [NLnetLabs/nsd#19]
Hi,

While fuzzing nsd-checkzone with American Fuzzy Lop, I found an out-of-bounds read caused by improper validation of array index, in the rdata_maximum_wireformat_size() function, in rdata.c L873.

Attaching a reproducer (gzipped so GitHub accepts it), issue can be reproduced by running:

nsd-checkzone all.rr zone01

[zone01.gz](https://github.com/NLnetLabs/nsd/files/3339077/zone01.gz)

**Comment by wcawijngaards** [comment]
Thanks for the report!  The type SIG was using the parse for type RRSIG, but the internal definition syntax used a different type DNAME conversion, this caused the mismatch and failure; a name allocated in one manner but later used in another manner.
