### ISSUE TITLE
nsd-control reconfig core dump

### ISSUE THREAD

**Issue by csumushu** [NLnetLabs/nsd#198]
After setting the cpu affinity, call nsd-control reconfig to get a core dump, and the nsd process can be restarted normally. My operating system is ubuntu and the nsd version is 4.3.8.
My configuration is as follows

server:
    do-ip4: yes
    do-ip6: yes
    username: nsd
    interface: eth1@5356
    server-count: 2
    reuseport: yes
    zonesdir: "/etc/nsd/"
    logfile: "/var/log/nsd.log"
    pidfile: "/run/nsd.pid"
    database: ""
    xfrdfile: ""
    zonefiles-write: 10
    cpu-affinity: 0 1
    server-1-cpu-affinity: 0
    server-2-cpu-affinity: 1

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-port: 8952
    server-key-file: "/etc/nsd/nsd_server.key"
    server-cert-file: "/etc/nsd/nsd_server.pem"
    control-key-file: "/etc/nsd/nsd_control.key"
    control-cert-file: "/etc/nsd/nsd_control.pem"

include: "/etc/nsd/tsig/*.tsig"
include: "/etc/nsd/conf.d/*.conf"

**Comment by wcawijngaards** [comment]
The patch fixes it by initializing the cpu affinity parse and allocation information. Thanks for the report!

It was crashing on reading the cpu affinity configuration information and then an uninitialised use of allocated variables.

**Comment by csumushu** [comment]
> The patch fixes it by initializing the cpu affinity parse and allocation information. Thanks for the report!
> 
> It was crashing on reading the cpu affinity configuration information and then an uninitialised use of allocated variables.

Do I need to modify the configuration file or modify the code? How to modify the code? I need to call nsd-control reconfig when setting cpu affinity. thank you very much.

**Comment by csumushu** [comment]
> The patch fixes it by initializing the cpu affinity parse and allocation information. Thanks for the report!
> 
> It was crashing on reading the cpu affinity configuration information and then an uninitialised use of allocated variables.

Thank you very much for helping me
