### ISSUE TITLE
nsd.conf manpage still contains references to master/slave

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/nsd#201]
This section still refers to master/slave:
https://github.com/NLnetLabs/nsd/blob/c888d317b9b959fbb8613758550e5c93282a19f5/nsd.conf.5.in#L942

Solution: Change to primary/secondary

**Comment by janstary** [comment]
Happy anniversary!

```
$ grep -Fr master * | wc -l
    2334
```

**Comment by k0ekk0ek** [comment]
Should be fixed with #371.
