### ISSUE TITLE
build fail. configparser contain c99 style.

### ISSUE THREAD

**Issue by yisizawa** [NLnetLabs/nsd#222]
### environment
CentOS 7.9
NSD 4.6.0

### command
git checkout NSD_4_6_0_REL
autoreconf
./configure --with-libevent --with-user=nsd --with-pidfile=/var/run/nsd/nsd.pid
make

### make error
```
./configparser.y: In function ‘c_parse’:
./configparser.y:1062:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for(struct component *i = $2; i; i = i->next) {
       ^
./configparser.y:1062:7: note: use option -std=c99 or -std=gnu99 to compile your code
./configparser.y:1069:33: error: redefinition of ‘i’
       for(struct component *j, *i = $2; i; i = j) {
                                 ^
./configparser.y:1062:29: note: previous definition of ‘i’ was here
       for(struct component *i = $2; i; i = i->next) {
                             ^
./configparser.y:1069:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for(struct component *j, *i = $2; i; i = j) {
       ^
make: *** [configparser.o] Error 1
```

I look #71 remove c99 style code.
or c99 enable autoreconf.

**Comment by k0ekk0ek** [comment]
Thanks for the report @yisizawa! This has been discussed on #219. I'll look into adding the flag.

**Comment by k0ekk0ek** [comment]
@yisizawa, using `AC_PROG_CC_STDC` make `autoconf` check for the newest C version and work it's way down. For CentOS 7, it makes it so that `-std=c99` is added as an argument automatically. When testing in a VM, that solved the issue for me.

**Comment by yisizawa** [comment]
Thanks. Build it later.

**Comment by yisizawa** [comment]
Build OK. Thanks.

I wait marge master.

**Comment by k0ekk0ek** [comment]
Thanks for testing!
