### ISSUE TITLE
Couldnot compile zone file.

### ISSUE THREAD

**Issue by anish9991** [NLnetLabs/nsd#235]
I have installed NSD v-4.3.6 in my Alpine Linux 3.14 vm. I could not find the **nsdc** package to compile the zone file. Is it not shipped with the package. Where do I find the nsdc package, or how do I compile the zone file. I am following the setup guide provided in the u/m link https://wiki.alpinelinux.org/wiki/Setting_up_nsd_DNS_server. I am setting up an authoritative-only dns server for my office LAN.

**Comment by wcawijngaards** [comment]
The `nsdc` utility is from older versions of NSD. The NSD 4.x versions can have nsd read the zonefile. In recent releases the `nsd-checkzone` utility can be used to parse a zone file to see if it has errors.

**Comment by anish9991** [comment]
Thanks for replying at the earliest. The nsd-checkzone shows no error, prints it properly, but the /var/lib/nsd.db file is not created neither the log file is created. The path for both are mentioned in the /etc/nsd/nsd.conf file. Can you please guide me how I can build this db file and how can I map the log file.

**Comment by wcawijngaards** [comment]
The nsd-checkzone utility only checks for errors. The zone is loaded by nsd itself, when it is started. The nsd.db file is not created by an outside utility. The setting `database: ""` is a good option to use. If set like that no nsd.db file is used. The zonefile is read by nsd, and for secondary servers, the zonefile is written when it gets updated.

The nsd.db file was created by an outside utility, nsdc, in older versions of NSD. But not in the recent versions, 4.x.

**Comment by anish9991** [comment]
Thank you for the quick response and support Sir, I got it working, Mistake in configuration file was the issue. Thanks Once again.

**Comment by anish9991** [comment]
Just left the office now. Will try again tomorrow and let you know. Thank
you once again for giving fast response.
