### ISSUE TITLE
NSD zone verifier logging prefix

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/nsd#240]
The NSD zone verifier logs all output via syslog, but there is little or no indication what log output comes from NSD itself and the validator. Can some sort of prefix be added?

(requested by @jschlyter )

**Comment by jschlyter** [comment]
I guess this will be implemented at https://github.com/NLnetLabs/nsd/blob/master/verify.c#L122 ?

**Comment by wtoorop** [comment]
> I guess this will be implemented at https://github.com/NLnetLabs/nsd/blob/master/verify.c#L122 ?

Indeed! What are you thinking, a configurable prefix?

**Comment by jschlyter** [comment]
> > I guess this will be implemented at https://github.com/NLnetLabs/nsd/blob/master/verify.c#L122 ?
> 
> Indeed! What are you thinking, a configurable prefix?

Just `verify-stdout:` or similar is good. other verifier ops are logged as `verify:` it seems.

**Comment by johanix** [comment]
Including the zone name could be useful. Obviously someone that writes their own verifier can easily do that in the verifier. But the usefulness of the prefix is 
- When using standard tools for verification
- For the case where the verifier crashes and you'd like to know zone triggered the crash.

Johan

**Comment by jschlyter** [comment]
@wtoorop do you want a PR?

**Comment by wtoorop** [comment]
> @wtoorop do you want a PR?

I think something configurable would fit all situations best. Maybe with some string processing similar as with the zonefile option (i.e. %s is replaced with the zone name etc.)
If you want to give that a shot, then a PR will be appreciated yes. Otherwise I'll just do it when there is a free moment...

**Comment by k0ekk0ek** [comment]
Thought I'd tackle this one while I was at it. Chose to prefix messages with `verifier: `, which fits the other messages nicely (IMHO)

**Comment by jschlyter** [comment]
You want the prefix for all lines, both first and continuation, I assume.

**Comment by k0ekk0ek** [comment]
@jschlyter, indeed :sweat_smile:. Oversight on my part.
