### ISSUE TITLE
manpages contain unreplaced @date@ and @version@

### ISSUE THREAD

**Issue by janstary** [NLnetLabs/nsd#242]
Currently, all four manpages contain @date@ and or @version@,
see the output of `grep -E '@(date|version)' *.8{,.in}`.

This shouldn't be there in the first place: a date is a part of the manpage itself,
to be changed whenever someone changes the manpage; and nobody needs
two versions of the same manpage installed.

Makefile creates `*.8` from `*.8.in` by sed'ing the @variables@;
but rather than adding @date@ and @version@ to the list,
let's please remove these from the manpages.

**Comment by janstary** [comment]
https://github.com/NLnetLabs/nsd/pull/243

**Comment by janstary** [comment]
(Testing: it's @date not @date so why does github change that?)

**Comment by janstary** [comment]
`@date` not @date ; ah.

**Comment by k0ekk0ek** [comment]
Thanks @janstary! Please allow us to pick this one up once we've switched to Sphinx for generating man pages.

**Comment by k0ekk0ek** [comment]
I've added them to `$(EDIT)` in `Makefile.in`. `makedist.sh` the script we use to create releases actually does replace them. Anyway, the `Makefile` does so now too, closing this issue.
