### ISSUE TITLE
The online documentation is still 4.3.9

### ISSUE THREAD

**Issue by janstary** [NLnetLabs/nsd#246]
https://nsd.docs.nlnetlabs.nl/en/latest/ is seven releases behind.

**Comment by k0ekk0ek** [comment]
Hi @janstary! Thank you for notifying us of the issue. As it happens, @gthess has done a lot of work to solve this exact problem for Unbound. NSD will eventually adopt the same mechanisms as (sort-of) indicated on #244. Please allow me to mark this one as duplicate and close it for now.
