### ISSUE TITLE
Make catalog zone configurable

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/nsd#250]
As discussed yesterday with @Koenvh1 , we've thought of just `catalog: <pattern name>` as how to configure a catalog consumer (and `catalog-from: <pattern-name>` as how to configure a catalog producer). The option can be part of a `pattern:` (or `zone:`) section. The options turns the zone or zone configured with the pattern in a Catalog zone consumer which will add and delete member zones with the given pattern.

- [x] Implement the `catalog: <pattern name>` configuration option to be configured in `pattern:` and `zone:` section
- [x] Document the option in the man page
- [x] Make a tpkg test for the option

**Comment by wtoorop** [comment]
@Koenvh1 volgens mij heb je consumer en producer omgedraaid in de manpage en example config :)
Misschien ook leuk om aan de test toe te voegen dat je niet `catalog:` en `catalog-from:` tegelijk kan hebben.

**Comment by Koenvh1** [comment]
Oh whoops. Should be correct now with f9bacf68beb636eac3a9c11a550f152d55ea2341 and 273c3172dd71cfcdb229478b5df19246e3c11e52.

**Comment by wtoorop** [comment]
Thanks @Koenvh1

Few open issues:

- [x] The `catalog` and `catalog_from` attributes need to be initialized (with NULL) when a new struct is created.
- [ ] We also need marshalling and unmarshalling of the options for `nsd-control reconfig` and `nsd-control repattern` to work.
- [ ] We also need to address the issues when one pattern includes two other patterns, one with a `catalog:` option and one with a `catalog-from:` option.
