### ISSUE TITLE
`nsd-control write` says "ok" despite permission problem

### ISSUE THREAD

**Issue by cweiske** [NLnetLabs/nsd#264]
`nsd-control write` says `ok` even if errors occur when writing the zone file.

I used nsd to transfer zones from my old tinydns server and wanted to write the zone files. It said all is fine:
```
$ nsd-control write example.org
ok
```

Unfortunately the zone file was not written in my configured `zonesdir`. Upon inspecting nsd's logs I saw:

> nsd[48816]: cannot write zone example.org file example.org.zone~: Permission denied

The [manual](https://nsd.docs.nlnetlabs.nl/en/latest/manpages/nsd-control.html) says nothing about nsd-control not returning the actual command execution result, so I expect that `nsd-control` tells me if something is wrong.

Please let either `nsd-control` tell me that the `write` command failed, or document this behavior in the manual.

**Comment by k0ekk0ek** [comment]
Hi @cweiske, looking at the code, that is indeed the case. I agree that ideally `nsd-control` returns whether or not the zone was written. Unfortunately, that is not an easy fix. The reason for that is that execution of the command is asynchronous. `nsd-control` will connect and `nsd` puts the command in a queue, to be executed on reload. Once the server process reloads (different process), it will read the instruction from the queue and do the action. The result of the command is not communicated back to the process that `nsd-control` is connected to.

With that in mind, I'm also not completely sure we want to implement whether the file is actually written. The reason being that the reload may take a "long" time, especially with corrupt xfrs and zone verification enabled (how long that takes depends on the command being executed to verify).

It may be a better idea to update `nsd-control zonestatus` to include whether the file is on disk. Also not a trivial task, but at least we don't have to make nsd blocking with regard to queue handling. We can of course add an option to instruct `nsd-control` to wait until zonestatus returns `on-disk-after-last-write-command`. In any case, updating the manual to state current behavior is a good idea.

**Comment by cweiske** [comment]
Not using "ok" as status message would help as well. It could say something along the lines of "command queued".

Adding a "--sync" option to wait for the result could also be an option, but I do not think that the implementation effort is worth the benefit.

**Comment by k0ekk0ek** [comment]
Reading through `remote.c`, `ok` seems to indicate command was accepted rather than successful. I chose not to update the response because users may have scripts that depend on the output. A small update to the `nsd-control` manpage should help avoid confusion for new users.

@cweiske, I'll leave this issue open if that's ok with you. We add synchronous operation in the future as an extra feature. It may prove useful for scripted use (e.g. for #259).
