### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [NLnetLabs/nsd#270]
I would like to point out that identifiers like “[`_DNS_H_`](https://github.com/NLnetLabs/nsd/blob/53b35c5c61607751b71ad22cbf9016c93cf23446/dns.h#L10 "Update candidate")” and “[`_IXFR_H_`](https://github.com/NLnetLabs/nsd/blob/bae280a2965a7e94ed28bf5724cb8613ae67dbd6/ixfr.h#L10 "Another update candidate")” [do not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by wcawijngaards** [comment]
It is nicer to not collide, potentially. The fix should remove the issue.

Thanks for the report!

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/NLnetLabs/nsd/commit/b7fa86fa2d6ceab14282b97df60eebf5cba064f5 "Renaming of include guards").
