### ISSUE TITLE
nsd.conf manpage outdated with 4.5.0

### ISSUE THREAD

**Issue by and0x000** [NLnetLabs/nsd#272]
The release for NSD 4.5 mentions new config file options `create-ixfr` and `store-ixfr`

https://github.com/NLnetLabs/nsd/releases/tag/NSD_4_5_0_REL

Neither of these options is documented in the current version of the nsd.conf manpage.

https://github.com/NLnetLabs/nsd-manual/blob/main/source/manpages/nsd.conf.rst

**Comment by k0ekk0ek** [comment]
Hi @and0x000! Sorry for the overdue reply. You're partially right :slightly_smiling_face:. The manpage documents the option, but the online documentation indeed lags behind. We have to look into automating that process.

**Comment by ttyS4** [comment]
Please do.

**Comment by k0ekk0ek** [comment]
This is fixed once #371 is merged (if approved).

**Comment by k0ekk0ek** [comment]
We now generate the online documentation from the `nsd` repository using `mandoc` to convert the actual manual pages to html. Thanks for reporting @and0x000!
