### ISSUE TITLE
Official Docker Image

### ISSUE THREAD

**Issue by nbish11** [NLnetLabs/nsd#285]
What are your thoughts on adding docker support? Both Unbound and NSD would be great to have as officially maintained docker images and some of your other projects already have docker support. I have an example repository over at [docker-nsd](https://github.com/nbish11/docker-nsd). I am more than happy to create a pull request and help to continue to maintain the image. (I would prefer to contribute here rather than have a separate fork.)

**Comment by k0ekk0ek** [comment]
Hi @nbish11! Thank you for bringing this to our attention. We'd love to add a reference in `contrib` for this, but prefer not to ship an official Docker image at this point. The reason for that is that there are too many configuration parameters and there's no one recommended way that is guaranteed to work for every user. Adding it to `contrib` is a good solution in situations like this. Issuing a PR against `contrib/Docker` (or similar) is probably the best way forward? Just adding a link to `contrib/README.md` is another possibility.

**Comment by nbish11** [comment]
Thanks [k0ekk0ek](https://github.com/k0ekk0ek). I will open a PR against contrib a little later to close this issue.

Your not wrong about the config options. I've actually 'borrowed' your docker magic build technique from the krill library to allow NSD to be built for cpu or memory optimisation; as even for me, NSD needs to be built differently, depending on the project.

**Comment by k0ekk0ek** [comment]
Closing this issue.
