### ISSUE TITLE
NULL pointer dereference in rdata_atom_size()

### ISSUE THREAD

**Issue by fcambus** [NLnetLabs/nsd#29]
Hi,

While fuzzing nsd-checkzone with Honggfuzz, I found a NULL pointer dereference in the rdata_atom_size() function.

I believe it was introduced by commit b4528a39f740cb5d39717d0b7611c35283b4735c.

Attaching a reproducer (gzipped so GitHub accepts it): [zone03.gz](https://github.com/NLnetLabs/nsd/files/3451665/zone03.gz)

Issue can be reproduced by running:

```
nsd-checkzone all.rr zone03
```

In namedb.h [L347](https://github.com/NLnetLabs/nsd/blob/master/namedb.h#L347) returning `*atom.data` results in a NULL pointer dereference because `atom.data` ends up being NULL:

```
#0  0x00000dd0a0deb360 in rdata_atom_size (atom={domain = 0x0, data = 0x0}) at namedb.h:347
347             return *atom.data;
```

**Comment by wcawijngaards** [comment]
Thanks!  Fixed, the NULL is because of the earlier parse error (introduced by the fuzzer in the hex glob).
