### ISSUE TITLE
NULL pointer dereference in domain_dname()

### ISSUE THREAD

**Issue by fcambus** [NLnetLabs/nsd#30]
Hi,

While fuzzing nsd-checkzone with Honggfuzz, I found a NULL pointer dereference in the domain_dname() function.

I believe it was introduced by commit b4528a39f740cb5d39717d0b7611c35283b4735c.

Attaching a reproducer (gzipped so GitHub accepts it): [zone04.gz](https://github.com/NLnetLabs/nsd/files/3451679/zone04.gz)

Issue can be reproduced by running:

```
nsd-checkzone all.rr zone04
```

In namedb.h [L270](https://github.com/NLnetLabs/nsd/blob/master/namedb.h#L270) returning `domain->dname` results in a NULL pointer dereference because `domain` ends up being NULL:

```
#0  0x0000041f7a8f3e2b in domain_dname (domain=0x0) at namedb.h:270
270             return (dname_type *) domain->dname;
```

**Comment by wcawijngaards** [comment]
Hi again! Thanks for the fuzzing action, this reveals nice corner cases.  The domain name is missing and it tries to print it in the error message, but the earlier parse error makes the domain name NULL causing it to error in the error printout.  I added a check for the domain name working.
