### ISSUE TITLE
Deprecate "multi-master-check" in favour of "multi-primary-check"

### ISSUE THREAD

**Issue by anandb-ripencc** [NLnetLabs/nsd#308]
The config option `multi-master-check` contains the word `master`, which should be avoided, as per RFC 8499.

It would be nice if this option were called `multi-primary-check`. The previous option name could be retained as an alias for backwards compatibility.

**Comment by wcawijngaards** [comment]
The commit fixes that and also the text in nsd.conf man page and example config, and also the output for nsd-checkconf and allows the older syntax to be used interchangeably. The functionality of the option is otherwise unchanged. Thanks for the report!
