### ISSUE TITLE
NSD stats contain the terms "master" and "slave"

### ISSUE THREAD

**Issue by anandb-ripencc** [NLnetLabs/nsd#310]
Hi. I've just noticed that the stats output of `nsd-control stats` prints `zone.master` and `zone.slave`. Ideally, these should also be renamed to `primary` and `secondary`, but I can imagine that it would break scripts that parse the output.

Perhaps the stats could print `zone.primary` and `zone.secondary` in addition to the old names, so that scripts expecting the old names can continue to work.

I suggest the complete discontinuation of the master/slave terminology in a major update of NSD, such as version 5.

**Comment by wcawijngaards** [comment]
Thanks for the heads up. The fix committed changes that. It prints zone.primary and zone.secondary in addition to the old names. And documents that in the nsd-control man page. Also some other log outputs are updated and sample config and the contrib nsd munin script that uses the primary and secondary zone counts for display.
