### ISSUE TITLE
dbaccess.c, dbcreate.c, difffile.c and difffile.h

### ISSUE THREAD

**Issue by anandb-ripencc** [NLnetLabs/nsd#311]
From what I can see, the code in these files is no longer used by NSD. However, they are still being compiled and linked into the `nsd` binary. Is it time to remove them?

**Comment by k0ekk0ek** [comment]
These files are still very much required. `difffile.c` for example contains most of the code used handling tasklist items (IPC mechanism used in NSD). Perhaps you're assuming that with the removal of the on-disk binary database these can be removed(?) However, NSD still uses an in-memory database, so while we removed storing information on disk in binary form, the in-memory database remains unchanged.

**Comment by anandb-ripencc** [comment]
Ah okay, thanks for the explanation @k0ekk0ek! I'll close the issue.
