### ISSUE TITLE
Clarify the purpose of contrib/bug390.patch

### ISSUE THREAD

**Issue by Kumba42** [NLnetLabs/nsd#324]
There's an old patch sitting in the `contrib/` folder called `bug390.patch`.  The current GitHub repository does not have an issue with that high of a number yet, so it's a bit of a mystery as to what this patch is for.

The closest match I could find is [this ticket](https://github.com/PowerDNS/pdns/issues/814) for PowerDNS that referneces an old Bugzilla instance that NLnetlabs used to run on their home website that had an ID of #390, which seems to align with something the patch is doing:

> It appears bind version <9.9.0 requires extra NSEC3 records to validate positive wildcard queries. It would be nice to have a compatibility config switch/option and ability for pdns to serve these extra records that older bind versions require to properly validate.
> 
> Ref to same issue with NSD: https://www.nlnetlabs.nl/bugs-script/show_bug.cgi?id=390
> 

However, that Bugzilla instance no longer exists, so it's impossible to review it and see if it's applicable to a modern-day build of NSD.  Can someone evaluate whether this patch is still needed and, if it is, document what it's doing and/or maybe drop some history about it if info from the old Bugzilla instance is still available?  Thanks!

**Comment by wcawijngaards** [comment]
The bugzilla page explains that the patch was briefly useful, while bind had an error where it would need a superfluous NSEC3 record. The patch provides this record, until the time when bind could have been patched to upgrade and fix the issue. That was on 2011-10-26. And in 2013-05-16 there is note that BIND 9.9.0 correctly validates without needing this patch. At that time the patch became no longer necessary.

**Comment by wcawijngaards** [comment]
The commit fixes the text in contrib/README to explain the purpose of the patch. That has been fixed for some time now, so I guess the patch could be removed. But I am keeping it for the moment to make the documentation visible with it.
