### ISSUE TITLE
build fails due to missing simdzone (git head)

### ISSUE THREAD

**Issue by gene-git** [NLnetLabs/nsd#327]
Git master as of commit 65312f98615e78ffefb2e9bc7b9cac9486331f28 fails to build.

Problem is that the directory simdzone is empty.

I did build simdzone  and installed it into /usr/{include,lib} but this didn't help - configure doesn't yet know about it.

thanks.

**Comment by k0ekk0ek** [comment]
Hi @gene-git. Thanks for the report! simdzone is included as a subrepository and statically linked with NSD. The idea is that a certain version is shipped in the tarball. Should you want to build from master instead, which is possible, you should initialize the submodule and run `autoconf` in that directory too. Depending on your usecase, it may be better to stick to official releases(?) I'll update the `README.md` to reflect the changes in building from Git for convenience.

**Comment by gene-git** [comment]
Thanks - i totally missed that it was added as submodule - after adding it everything builds just fine.
 
I use releases in production but I also build git head daily.

thank you for patiently explaining what I missed!

Thank you for README updates as well. I'm sure it will be helpful.
