### ISSUE TITLE
TCP accept queues number

### ISSUE THREAD

**Issue by iruzanov** [NLnetLabs/nsd#329]
Hello coleagues!

I have reuseport-option specific question.
In nsd-config i set reuseport: yes
And set ip-address: 1.2.3.4
server-count: 10 (for example)

When i start NSD (under Linux), i can see the following:
ss -lntup | grep 1.2.3.4 | grep tcp
tcp    LISTEN  0       256                                  1.2.3.4:53                                          0.0.0.0:*                                   users:(("server 10",pid=1954522,fd=5),("server 9",pid=1954521,fd=5),("server 8",pid=1954520,fd=5),("server 7",pid=1954519,fd=5),("server 6",pid=1954518,fd=5),("server 5",pid=1954517,fd=5),("server 4",pid=1954516,fd=5),("server 3",pid=1954515,fd=5),("server 2",pid=1954514,fd=5),("server 1",pid=1954513,fd=5),("dnstap_collecto",pid=3518,fd=5),("main",pid=3517,fd=5),("xfrd",pid=3509,fd=5))
So, i have single TCP-queue.

In contrast, Unbound with the same settings creates expected 10 TCP-queues:
tcp    LISTEN  0       256                                   1.2.3.4:53                                          0.0.0.0:*                                   users:(("unbound",pid=3935529,fd=472))
[...]
tcp    LISTEN  0       256                                   1.2.3.4:53                                          0.0.0.0:*                                   users:(("unbound",pid=3935529,fd=16))

But, if in nsd-config i set ip-address: multiple times (not greater than server-count), in this example, 10, i have needed 10 TCP-queues:
ip-address: 1.2.3.4 (1-st option)
[...]
ip-address: 1.2.3.4 (10-th option)

And ss -lntup | grep 1.2.3.4 | grep tcp gives the following output:
tcp   LISTEN 0      256                    1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 10",pid=94757,fd=125),("nsd: server 9",pid=94756,fd=125),("nsd: server 8",pid=94755,fd=125),("nsd: server 7",pid=94754,fd=125),("nsd: server 6",pid=94753,fd=125),("nsd: server 5",pid=94752,fd=125),("nsd: server 4",pid=94751,fd=125),("nsd: server 3",pid=94750,fd=125),("nsd: server 2",pid=94749,fd=125),("nsd: server 1",pid=94748,fd=125),("nsd: main",pid=88311,fd=125),("nsd: xfrd",pid=88310,fd=125))
[...]
tcp   LISTEN 0      256                    1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 10",pid=94757,fd=107),("nsd: server 9",pid=94756,fd=107),("nsd: server 8",pid=94755,fd=107),("nsd: server 7",pid=94754,fd=107),("nsd: server 6",pid=94753,fd=107),("nsd: server 5",pid=94752,fd=107),("nsd: server 4",pid=94751,fd=107),("nsd: server 3",pid=94750,fd=107),("nsd: server 2",pid=94749,fd=107),("nsd: server 1",pid=94748,fd=107),("nsd: main",pid=88311,fd=107),("nsd: xfrd",pid=88310,fd=107))

So, the question - does multiple ip-address: options with the same IP provide right solution to give TCP-queues as much as value in server-count: option when we use reuseport: yes? And only one side effect that in this case i have "server-count:" (beacuse i set ip-address: "server-count:" times) times more UDP-sockets in the system (according to manual for nsd.conf).

Thank you for the help in advance!

**Comment by wcawijngaards** [comment]
Turns out this was disabled in NSD 4.1.7, `Fix TCP responses when REUSEPORT is in use by turning it off`. I guess that was because the combination of TCP and reuseport was not working at the time. We could enable it again, see if that is nicer, what with newer code deployed, maybe that is fine, also since it is in other software?

Having several ip-address options for the same address is not the solution for reuseport for TCP, because it was disabled. If you did, something like `ip-address: 1.2.3.4 servers="1"` .. `ip-address: 1.2.3.4 servers="10"` likely opens a tcp socket for every server. But that is using the configurable server and cpu-affinity for listening sockets options for a workaround.

**Comment by iruzanov** [comment]
> Turns out this was disabled in NSD 4.1.7, `Fix TCP responses when REUSEPORT is in use by turning it off`. I guess that was because the combination of TCP and reuseport was not working at the time. We could enable it again, see if that is nicer, what with newer code deployed, maybe that is fine, also since it is in other software?
> 
> Having several ip-address options for the same address is not the solution for reuseport for TCP, because it was disabled. If you did, something like `ip-address: 1.2.3.4 servers="1"` .. `ip-address: 1.2.3.4 servers="10"` likely opens a tcp socket for every server. But that is using the configurable server and cpu-affinity for listening sockets options for a workaround.

Thank you for detailed explanation, Wouter!
And, yes, i tried to do the following:
ip-address: 1.2.3.4 servers="1"` .. `ip-address: 1.2.3.4 servers="10
This works fine for TCP:
tcp   LISTEN 0      256                    1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 10",pid=105257,fd=125),("nsd: main",pid=105192,fd=125),("nsd: xfrd",pid=105191,fd=125))                                                                                                                                                                                                                                                                                              
tcp   LISTEN 0      256                    1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 9",pid=105256,fd=123),("nsd: main",pid=105192,fd=123),("nsd: xfrd",pid=105191,fd=123))                                                                                                                                                                                                                                                                                               
tcp   LISTEN 0      256                    1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 8",pid=105255,fd=121),("nsd: main",pid=105192,fd=121),("nsd: xfrd",pid=105191,fd=121))                                                                                                                                                                                                                                                                                               
tcp   LISTEN 0      256                    1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 7",pid=105254,fd=119),("nsd: main",pid=105192,fd=119),("nsd: xfrd",pid=105191,fd=119))                                                                                                                                                                                                                                                                                               
tcp   LISTEN 0      256                    1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 6",pid=105253,fd=117),("nsd: main",pid=105192,fd=117),("nsd: xfrd",pid=105191,fd=117))                                                                                                                                                                                                                                                                                               
tcp   LISTEN 0      256                    1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 5",pid=105252,fd=115),("nsd: main",pid=105192,fd=115),("nsd: xfrd",pid=105191,fd=115))                                                                                                                                                                                                                                                                                               
tcp   LISTEN 0      256                    1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 4",pid=105251,fd=113),("nsd: main",pid=105192,fd=113),("nsd: xfrd",pid=105191,fd=113))                                                                                                                                                                                                                                                                                               
tcp   LISTEN 0      256                    1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 3",pid=105250,fd=111),("nsd: main",pid=105192,fd=111),("nsd: xfrd",pid=105191,fd=111))                                                                                                                                                                                                                                                                                               
tcp   LISTEN 0      256                    1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 2",pid=105249,fd=109),("nsd: main",pid=105192,fd=109),("nsd: xfrd",pid=105191,fd=109))                                                                                                                                                                                                                                                                                               
tcp   LISTEN 0      256                    1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 1",pid=105248,fd=107),("nsd: main",pid=105192,fd=107),("nsd: xfrd",pid=105191,fd=107))                         

But does not work for UDP:
udp   UNCONN 0      0                      1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 2",pid=105298,fd=257),("nsd: main",pid=105192,fd=257),("nsd: xfrd",pid=105191,fd=257))                                                                                                                                                                                                                                                                                               
udp   UNCONN 0      0                      1.2.3.4:53        0.0.0.0:*    users:(("nsd: main",pid=105192,fd=256),("nsd: xfrd",pid=105191,fd=256))                                                                                                                                                                                                                                                                                                                                   
udp   UNCONN 0      0                      1.2.3.4:53        0.0.0.0:*    users:(("nsd: main",pid=105192,fd=124),("nsd: xfrd",pid=105191,fd=124)) 
[...]

vs. working UDP (with just ip-address: options, without servers=x):
udp   UNCONN 0      0                      1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 2",pid=106222,fd=265),("nsd: main",pid=106160,fd=265),("nsd: xfrd",pid=106159,fd=265))                                                                                                                                                                                                                                                                                               
udp   UNCONN 0      0                      1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 2",pid=106222,fd=264),("nsd: main",pid=106160,fd=264),("nsd: xfrd",pid=106159,fd=264))                                                                                                                                                                                                                                                                                               
udp   UNCONN 0      0                      1.2.3.4:53        0.0.0.0:*    users:(("nsd: server 2",pid=106222,fd=263),("nsd: main",pid=106160,fd=263),("nsd: xfrd",pid=106159,fd=263))
[...]

I verified with dig ... @1.2.3.4 command.

**Comment by wcawijngaards** [comment]
Did you set `reuseport: yes` with that output?

**Comment by iruzanov** [comment]
> Did you set `reuseport: yes` with that output?

Yes i did. `resuseport: yes`
With `reuseport: no` i got "address already in use",

**Comment by wcawijngaards** [comment]
Perhaps with the commit this is better. It enables TCP and reuseport, so that with the `reuseport: yes` option, and just one ip-address specification needed, it can open tcp sockets with reuseport for every server process.

**Comment by iruzanov** [comment]
> Perhaps with the commit this is better. It enables TCP and reuseport, so that with the `reuseport: yes` option, and just one ip-address specification needed, it can open tcp sockets with reuseport for every server process.

BIG-BIG thank you!
