### ISSUE TITLE
segfault in libc-2.29.so

### ISSUE THREAD

**Issue by bes-internal** [NLnetLabs/nsd#33]
```
Aug  5 15:43:46 home nsd[145459]: control cmd:  stats
Aug  5 15:48:46 home nsd[145459]: new control connection from 127.0.0.1
Aug  5 15:48:46 home nsd[145459]: control cmd:  stats
Aug  5 15:53:46 home nsd[145459]: new control connection from 127.0.0.1
Aug  5 15:53:46 home nsd[145459]: control cmd:  stats
Aug  5 15:53:46 home nsd[145460]: process 171339 terminated with status 11
Aug  5 15:53:46 home kernel: [2179729.697922] nsd[171339]: segfault at 5569a65eccd8 ip 00007fe293b15a90 sp 00007ffc90343960 error 4 in libc-2.29.so[7fe293aac000+159000]
Aug  5 15:53:46 home kernel: nsd[171339]: segfault at 5569a65eccd8 ip 00007fe293b15a90 sp 00007ffc90343960 error 4 in libc-2.29.so[7fe293aac000+159000]
```

**Comment by wcawijngaards** [comment]
If I repeat that, eg. ask stats for several times, it does not happen for me.  Is this with a recent version (eg. 4.2.1?) and, can you repeat the failure?  What are the details of this setup that cause it to fail for you?  What is the failure (eg. start with` valgrind --trace-children=yes nsd -d  ` and then it stays attached to that console, until you quiet, you could `>output 2>&1` on that line to get the stdout and stderr output) ?

**Comment by bes-internal** [comment]
Yes, this 4.2.1. Randomly crashed 1-2 times a day (in stat I expected, because continue to serv)
My Glibc was built without debugging information, so it rebuilt it and valgrind no longer out any requirements. But if this will be needed I will rebuild it with debugsyms, strlen.

I lost this run on few days:
`valgrind --trace-children=yes /usr/sbin/nsd -c /etc/nsd/nsd.conf -d >output 2>&1`
there is [output.gz](https://github.com/NLnetLabs/nsd/files/3486562/output.gz)

I was not found any segfault in logs (wan in dmesg), but maybe valgring devour it.
I was not found something interesting about libc- around "info: control cmd:  stats" but this " Use --track-origins=yes to see where uninitialized values come from. ERROR SUMMARY: 44 errors from 15 contexts (suppressed: 0 from 0)"

**Comment by wcawijngaards** [comment]
The uninitialized values are not the problem here, they are due to the openssl build.  There are debug options to stop them. So we can ignore them here.
But the double free of a 4k block is very interesting.  No debug info for the nsd executable, unfortunately. If you have a debug build (that is identical in every way) `addr2line` could be used to create the function names.  Otherwise still a very useful piece of information, thank you.

**Comment by bes-internal** [comment]
probably with debug, if not, then I'll try to rebuild [output-wdbg.gz](https://github.com/NLnetLabs/nsd/files/3491835/output-wdbg.gz)

**Comment by wcawijngaards** [comment]
Thanks for the stack printout, that helped me find the bug.  It was introduced in 4.2.1, and is related to cleanup after the process exits.  Apart from logs, it should not have interrupted clients.
The fix is in https://github.com/NLnetLabs/nsd/commit/f45ceb21d77b53191888b8a8c6c91a1a37dea7ef
