### ISSUE TITLE
RFC8482 behavior documentation

### ISSUE THREAD

**Issue by and0x000** [NLnetLabs/nsd#334]
NSD for ANY requests behaves according to [RFC 8482 4.1](https://www.rfc-editor.org/rfc/rfc8482#section-4.1)

This is documented in the code: https://github.com/NLnetLabs/nsd/blob/a9ffdb622e56ee92cd0135aa2aad7deee637ad39/query.c#L1024-L1029

However, there is no documentation of this on [NSD's RFC compliance list](https://www.nlnetlabs.nl/projects/nsd/rfc-compliance/) nor in the context of the `refuse-any` configuration option.

**Comment by wcawijngaards** [comment]
The documentation is added to the `refuse-any` text segment. Also the NSD RFC compliance list is updated. Thank you for the report!
