### ISSUE TITLE
Update simdzone

### ISSUE THREAD

**Issue by thedix** [NLnetLabs/nsd#344]
Please update simdzone to the latest commit.
There was a problem with compiling nsd 4.10.0 on BSD systems, it was fixed in NLnetLabs/simdzone#202.

**Comment by wcawijngaards** [comment]
Sure, I updated the simdzone version used by the nsd repository to the latest commit on simdzone; the endian fix merge. This includes a number of bug fixes.

**Comment by thedix** [comment]
@wcawijngaards Thank you!
