### ISSUE TITLE
Adjust verbosity for TLS (+TCP) to be 5

### ISSUE THREAD

**Issue by jaredmauch** [NLnetLabs/nsd#347]
As we are seeing an increase in TCP queries this creates excessive logging when we would not want those events logged at lower levels while we would want to see other logs.  Move the TLS+TCP to be verbosity level 5

**Comment by wcawijngaards** [comment]
Verbosity level 3 is a little low for that output. This changes the output of `TLS handshake: connection closed prematurely` and `TLS handshake succeeded.`. If there are more messages that need to change verbosity level, those would need to be changed too.
