### ISSUE TITLE
4.2.2 - TLS handshake failed

### ISSUE THREAD

**Issue by jaredmauch** [NLnetLabs/nsd#38]
```
Sep 26 07:36:41 puck nsd[1576860]: TLS handshake failed
Sep 26 07:36:41 puck nsd[1576539]: [2019-09-26 07:36:41.561] nsd[1576860]: error: TLS handshake failed
Sep 26 07:36:41 puck nsd[1576860]: TLS handshake failed
Sep 26 07:36:41 puck nsd[1576539]: [2019-09-26 07:36:41.595] nsd[1576860]: error: TLS handshake failed
Sep 26 07:36:47 puck nsd[1576860]: TLS handshake failed
Sep 26 07:36:47 puck nsd[1576539]: [2019-09-26 07:36:47.577] nsd[1576860]: error: TLS handshake failed
Sep 26 07:36:47 puck nsd[1576860]: TLS handshake failed
Sep 26 07:36:47 puck nsd[1576539]: [2019-09-26 07:36:47.619] nsd[1576860]: error: TLS handshake failed
```
Logs contain the above messages without any further details.  I'm thinking it should provide the IP address in the log message if possible, as well as perhaps reducing duplicate logs or it being a debug/traceoption

**Comment by wcawijngaards** [comment]
Hi Jared,
Fixed this by logging the address and failure reason.  It also omits certain frequent ones, that were complained about for Unbound, from the logs, unless a high verbosity is used, then they are shown.
Let me know if this works out for you.
Best regards, Wouter

**Comment by wcawijngaards** [comment]
The error message looks like this ```error: TLS handshake failed from 127.0.0.1 crypto error:140940F4:SSL routines:ssl3_read_bytes:unexpected message```
