### ISSUE TITLE
log timestamps in ISO8601 format with timezone

### ISSUE THREAD

**Issue by pspacek** [NLnetLabs/nsd#383]
Version: NSD 4.10.1

This is a feature request to use standard timestamp format for NSD output, including timezone.

Why?
- Adding timezone would greatly simplify correlating logs from different servers.
- Maintaining custom parser is ... suboptimal.

NSD currently outputs:
```
+ nsd -c nsd.conf -d
[2024-09-24 18:11:29.157] nsd[264440]: notice: nsd starting (NSD 4.10.1)
```

It would be really great if it could output ISO8601 format:
```
2024-09-24T18:11:29.157+00:00 nsd[264440]: notice: nsd starting (NSD 4.10.1)
```

BTW Knot DNS uses the ISO format already.

I dunno if this is deemed an incompatible change or not, but if it is maybe an extra option to switch format could be introduced?

Thank you for considering this.

**Comment by wcawijngaards** [comment]
The log options `log-time-ascii: yes` and `log-time-iso: yes` can be enabled to produce ISO8601 timestamps in the log file. Thank you for the report!

**Comment by pspacek** [comment]
Thank you very much!
