### ISSUE TITLE
NSD 4.10.1 gpg signature unknown

### ISSUE THREAD

**Issue by EweSparky** [NLnetLabs/nsd#385]
Hi there,

The gpg signature for 4.10.1 is signed by `EE353E7D9F5299FEA8B33AB75B10751F1CD4BB2C`, but this isn’t listed on the [people page](https://nlnetlabs.nl/people/). Is this valid?

https://nlnetlabs.nl/downloads/nsd/nsd-4.10.1.tar.gz
https://nlnetlabs.nl/downloads/nsd/nsd-4.10.1.tar.gz.asc

Thanks.

**Comment by k0ekk0ek** [comment]
Hi @StuartMorrisAU! That would be my key:

```
gpg --verify nsd-4.10.1.tar.gz.asc nsd-4.10.1.tar.gz
gpg: Signature made Fri 02 Aug 2024 02:05:28 PM CEST
gpg:                using RSA key EE353E7D9F5299FEA8B33AB75B10751F1CD4BB2C
gpg: Good signature from "Jeroen Koekkoek <jeroen@koekkoek.nl>" [unknown]
gpg:                 aka "Jeroen Koekkoek <jeroen@nlnetlabs.nl>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9E32 AFD1 29E3 AB1D C5AB  34DE 7DE0 8345 DE34 009F
     Subkey fingerprint: EE35 3E7D 9F52 99FE A8B3  3AB7 5B10 751F 1CD4 BB2C
```

The link on the people page points you to the Ubuntu keyserver. Wouter signed my key too. It's valid :slightly_smiling_face:.

**Comment by EweSparky** [comment]
@k0ekk0ek apologies, my mistake. I only checked the people page instead of downloading the signature.

**Comment by k0ekk0ek** [comment]
No worries, it's good that you checked :+1:
