### ISSUE TITLE
Broken "Edit on GitHub" links on documentation page

### ISSUE THREAD

**Issue by melroy89** [NLnetLabs/nsd#393]
Hi,

I'm back again, again (sorry 😖 !). The button "Edit on GitHub" seems to be broken for both NSD as well as Unbound projects.

Example page: https://nsd.docs.nlnetlabs.nl/en/latest/zonefile.html

Clicking on the edit link, goes to: https://github.com/NLnetLabs/nsd/blob/master/source/zonefile.rst (broken link/incorrect)

It should have gone to the following link instead: https://github.com/NLnetLabs/nsd/blob/master/doc/manual/zonefile.rst

So the diff is `source/` vs `doc/manual/` in the documentation generation process. Again, same issue is present in other projects like Unbound documentation as well.

Kind regards,
Melroy van den Berg

**Comment by melroy89** [comment]
I think I found the issue in: https://github.com/NLnetLabs/nsd/blob/master/doc/manual/conf.py.in#L160

**Comment by wcawijngaards** [comment]
Thank you for the fix to the documentation edit button.
