### ISSUE TITLE
make (dist)clean does not delete config.h

### ISSUE THREAD

**Issue by dilyanpalauzov** [NLnetLabs/nsd#48]
./configure creates config.h, but neither "make clean”, nore “make distclean” deletes it.   The GNU coding standards convention is to delete with “make distclean” whatever “./configure” creates.  I use nsd 4.2.3.

GNU coding standards extract: https://www.gnu.org/prep/standards/html_node/Standard-Targets.html#Standard-Targets , see “distclean”.
 
The reproducing procedure is:

I download and unpack nsd-4.2.3. Then I go in the nsd-4.2.3 forder, call ./configure .  Then I call ”make disclean; make clean; mkdir build; cd build ;  ../configure --enable-mmap --enable-systemd --enable-recvmmsg --with-configdir=/etc/nsd --with-user=nsd ” . This fail because ../config.h. exists and deleting config.h, and re-invoking build/configure ... emits again that ../config.h exists.

So if I run ./configure in the in-source-tree, before doing out-of-source (VPATH) build, “make distclean” shall revert all side-effects of ./configure and let me later perfom VPATH build.

**Comment by wcawijngaards** [comment]
Hi! Thanks for the report.  Make distclean did not exist.  There is make realclean, that does delete config.h but also the created bison and lex files.  Added a distclean target that deletes the output of configure.  It does not delete the output of bison and flex, that is what realclean does too.  There is also devclean and it deletes also configure itself and config.h.in (you have to re-run autoconf, autoheader).
```
+distclean: clean
+       rm -f Makefile config.h config.log config.status
+       rm -f dnstap/dnstap_config.h
```
The dnstap header is also produced by configure (in certain cases).  Let me know if you want other content in the clean targets, but we seem to have a bunch of them, I appreciate there is a coding standard for it.

**Comment by dilyanpalauzov** [comment]
Created bison and flex files shall be deleted by target maintainer-clean, according to the GNU standards/make targets.

**Comment by wcawijngaards** [comment]
Okay, in https://github.com/NLnetLabs/nsd/commit/8ac077f76062717c53db7264d229b78c8d4e5d1a I added maintainer-clean too.  As an alias for realclean.  I think it is good to be similar to other open source projects to that package maintainers are not surprised and can find their way around more easily.

**Comment by wcawijngaards** [comment]
Also for Unbound in https://github.com/NLnetLabs/unbound/commit/f82f97199741a05cef5c2cd2d84b4fe24847a57a .
