### ISSUE TITLE
Option to force-reload a zone

### ISSUE THREAD

**Issue by madduck** [NLnetLabs/nsd#58]
Please provide a command with which all zones can be forcefully reinitialised from disk, short of restarting `nsd`. I.e. `nsd-control force-reload [zone]`, which skips the "has file been modified" check.

**Comment by k0ekk0ek** [comment]
Let's close this one. Should be no need for it once #57 is fixed? @madduck, feel free to reopen if I'm wrongly assuming you opened this issue because `$INCLUDE`s weren't tracked correctly.
