### ISSUE TITLE
GNU HURD and nsd.c:352:19: warning: cast from pointer to integer of different size

### ISSUE THREAD

**Issue by noloader** [NLnetLabs/nsd#74]
Hi Everyone,

I'm testing nsd master on GNU HURD. The HURD image is dated JAN 2020, and is fully patched. HURD is a GNU Linux operating system with a personality. It is also i386, not x86_64.

Bootstrap and configure go well. Below is the output of `make`.

```
gcc -I. -I/usr/local/include -g -O2 -flto -c nsd.c
nsd.c: In function ‘find_device’:
nsd.c:352:19: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  352 |    len = (size_t)((uintmax_t)colon - (uintmax_t)ifa->ifa_name);
      |                   ^
nsd.c:352:38: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  352 |    len = (size_t)((uintmax_t)colon - (uintmax_t)ifa->ifa_name);
      |                                      ^
```

I am not familiar with the use of the `uintmax_t` type. I believe the way to proceed is, (1) add `std=c99` compile option; or (2) cast the pointer to a `uintptr_t`. Though `uintptr_t` is optional, it is ubiquitous based on my testing.

(This was encountered after clearing https://github.com/NLnetLabs/nsd/issues/73).

**Comment by wcawijngaards** [comment]
Yes, thank you.  The `uintptr_t` is exactly the right fix.  Committed that.
