### ISSUE TITLE
Solaris and lex defines yy_current_buffer... lex: illegal option -- i

### ISSUE THREAD

**Issue by noloader** [NLnetLabs/nsd#77]
Hi Everyone,

I'm testing nsd master on Solaris 11.3 i86pc, fully patched. Solaris is a multiarch machine out of the box.

The `lex` test in `configure.ac` is producing some noise:

```
checking for flex... no
checking for lex... lex
checking lex output file root... lex.yy
checking lex library... -ll
checking whether yytext is a pointer... no
checking for bison... no
checking for byacc... no
checking if lex defines yy_current_buffer... lex: illegal option -- i
Usage: lex [-ewctvnVY] [-Q(y/n)] [file]
no
```

Oracle has good docs. You can find the man page at [`lex(1)` man page](https://docs.oracle.com/cd/E26502_01/html/E29030/lex-1.html).

**Comment by noloader** [comment]
It looks like `-i` is case-insensitive when used with [GNU] `lex`. Maybe you can move the insensitive-ness into `grep`:

```
-  $LEX -i -t conftest.lex >> conftest.c
-  if grep "^#define yy_current_buffer" conftest.c >/dev/null; then
+  $LEX -t conftest.lex >> conftest.c
+  if grep -i "^#define yy_current_buffer" conftest.c >/dev/null; then
```

`grep` is anemic on Solaris, too. But it is Posix and supports `-i`. See the [`grep(1)` man page](https://docs.oracle.com/cd/E26502_01/html/E29030/grep-1.html).

**Comment by noloader** [comment]
The patch above gets through `configure`. However, `make` has some problems:

```
$ make
gcc -I. -I/usr/local/include -g -O2 -flto -c answer.c
gcc -I. -I/usr/local/include -g -O2 -flto -c axfr.c
gcc -I. -I/usr/local/include -g -O2 -flto -c buffer.c
if test "lex" != ":"; then rm -f configlexer.c ;\
        echo '#include "configyyrename.h"' > configlexer.c ;\
        lex -i -t ./configlexer.lex >> configlexer.c ;\
fi
lex: illegal option -- i
Usage: lex [-ewctvnVY] [-Q(y/n)] [file]
*** Error code 1
make: Fatal error: Command failed for target `configlexer.c'
```

**Comment by wcawijngaards** [comment]
NSD needs flex installed to build.  For yacc the bison package.  These packages are available for Solaris too, just as autoconf (and so on) build tools.

Best regards, Wouter

**Comment by k0ekk0ek** [comment]
`byacc` can be used too, but `flex` is definitely a requirement, yes. I believe most platforms actually just ship `flex` for `lex` nowadays(?) As for moving the `-i` to `grep`, the `-i` for `lex` is there for matching patterns in the configuration files in a case insensitive manner, so it's not quite the same. If you want it to compile with actual `lex`, I'd welcome patches (an example can for doing things a bit differently can be found [here](https://github.com/k0ekk0ek/nsdconf/), notice that the lexer doesn't know about any options itself, which is the trick), but honestly I'd leave it alone. I've tried to make changes myself, you're better of writing a configuration parser. Dealing with all the differences between lex/flex and the integration with byacc/bison isn't worth it.

**Comment by noloader** [comment]
> As for moving the -i to grep, the -i for lex is there for matching patterns in the configuration files in a case insensitive manner, so it's not quite the same. 

Ack, that was an open question for me.

I haven't used lex and yacc since college (too many years ago). I'm not an asset for them :(
