### ISSUE TITLE
event_add failed. in cpsl

### ISSUE THREAD

**Issue by iiscjolly** [NLnetLabs/nsd#94]
Hi,

I am getting below error in my setup.
comm_point_start_listening: comm point start listening 1030
comm_point_start_listening: event_add failed. in cpsl.

As per my analysis, it's failing due to below check.

if(ev->ev_fd != -1 && ev->ev_fd >= ev->ev_base->capfd)
    return -1;

I would like to know, what is the reason for capping Max FD to 1024 (#define MAX_FDS 1024).
Will there be any impact if we increase this limit?

Thanks,
Janardhan.

**Comment by wcawijngaards** [comment]
This seems to be an issue for Unbound, and you posted it in NSD.

That said, you use the builtin event handler that uses select(2), that is what the MAX_FDS maximum refers to.  If you want to up that limit, compile with libevent, that is the default in more recent releases, just have libevent-dev installed to compile with it, or use the --with-libevent switch for configure.  Then the limit is removed and it already defaults to more than 1000 fds.

For NSD, it can also compile with libevent, by the way, to up that limit on the number of file descriptors.
